import type { Metadata } from "next";
import { Raleway} from "next/font/google";

const raleway = Raleway({
    subsets: ['latin'],
    weight: ['200','400','600', '700'], // Pick the weights you need
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className}`}
      >
        {children}
      </body>
    </html>
  );
}
